sudo: required
services:
  - docker

before_install:
  - docker build -t jessewalia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jessewalia/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-200982765440"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
